name: Infrastructure Cleanup
# on:  
#   push:
#     tags:
#       - 'failure-*'

jobs:
  destroy-green-on-failure:
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Destroy failing backend
        uses: dflook/terraform-destroy@v1
        with:
          path: util/terraform/backend
          workspace: ${{ github.head_ref }}
      
      - name: Destroy failing frontend
        uses: dflook/terraform-destroy@v1
        with:
          path: util/terraform/frontend
          workspace: ${{ github.head_ref }}
      
      - run: echo notify team!